[package]
name = "fraese"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-a = "8.0.0"
crossbeam = "0.8.2"
embedded-hal = "0.2.7"
rppal = "0.13.1"
tock-registers = "0.8.1"
